version: "3.3"
services:
  api:
    container_name: go-anytime
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/api:/go/src/api
